

default:
  contribute:
    comment:
      message: 'Thanks for contributing!'
  bug:
    comment:
      message: 'Thanks for reporting this bug!'


labels:
  'enhancement': contribute
  'bug': bug

