name: Add comment
on:
  issues:
    types:
      - labeled

jobs:
  add-comment:
    if: github.event.label.name == 'enhancement'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: checkout
        uses: actions/checkout@v2
        run: |
          git config user.name "qbot"
          git config user.email "<>"
      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thank you for your contribution! :sparkles:
